pathToFilesToRead = /N3
pathToOutputDirectoryFile = /N3/src/main/resources/assets/directory.txt
pathToEncryptedFile = /N3/src/main/resources/assets/encryptedFile.enc
pathToDecryptedFile = /N3/src/main/resources/assets/decryptedFile.txt